name: local_dukaan
description: To curb the spread of the novel Coronavirus, Social Distancing and Staying indoors are the only precautionary measures available. Introducing Local Dukaan, an app that allows you to create  your Order List and pick up the same from your nearby shop, at a time given by the shopkeeper. Now, you can conveniently minimise your exposure & interactions while being outdoors - peacefully buy your choice of grocery or medicine. Available on Android & iOS. Stay Home & Stay Safe.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.0+1
  intl: ^0.16.0
  firebase_auth: ^0.15.3+1
  flutter_signin_button: ^1.0.0
  cuberto_bottom_bar: ^1.1.0
  firebase_messaging: '^6.0.12'
  google_map_location_picker: ^3.2.1+2
  dart_geohash: ^1.0.2
  latlong: ^0.6.1
  map_launcher: ^0.4.3
  google_maps_flutter:
  url_launcher: any
  flutter_datetime_picker: ^1.3.5
  jiffy: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/localdukaan.png"

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - data/
